### ISSUE TITLE
route_translator breaks Rails partial collection caching?

### ISSUE THREAD

**Issue by richardvenneman** [enriclluelles/route_translator#134]
Hi,

First of all thanks for all the great work on this gem :pray:  Have been using it successfully in a lot of projects.

Currently having some issues with partial collection caching in a Rails 5 beta app. I Stumbled upon [a (now closed) issue at rails/rails](https://github.com/rails/rails/issues/24132) which described the same I'm experiencing. At the end of the day I could finally determine the error occurred when including the `route_translator` gem in my Gemfile.

Consider the following render statement (also note the explicit `cached` argument which is now required for multi fragment collection caching):

```erb
<%= render partial: 'projects/project', collection: @projects, as: :project, cached: true %>
```

This works fine in a vanilla Rails 5 beta3 app. However adding route_translator at the `rails5` branch produces the following error:

```
ActionView::Template::Error (undefined method `read_multi' for nil:NilClass
Did you mean?  readline):
    11:   </thead>
    12: 
    13:   <tbody>
    14:     <%= render partial: 'projects/project', collection: @projects, as: :project, cached: true %>
    15:   </tbody>
    16: </table>
    17: 
  
app/views/projects/index.html.erb:14:in `_app_views_projects_index_html_erb__932027715936146004_70231266540480'
  Rendered /Users/richard/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actionpack-5.0.0.beta3/lib/action_dispatch/middleware/templates/rescues/_source.html.erb (3.3ms)
  Rendered /Users/richard/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actionpack-5.0.0.beta3/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (1.6ms)
  Rendered /Users/richard/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actionpack-5.0.0.beta3/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (0.6ms)
  Rendered /Users/richard/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actionpack-5.0.0.beta3/lib/action_dispatch/middleware/templates/rescues/template_error.html.erb within rescues/layout (54.5ms)
  Rendered /Users/richard/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/web-console-3.1.1/lib/web_console/templates/_markup.html.erb (0.3ms)
  Rendered /Users/richard/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/web-console-3.1.1/lib/web_console/templates/_inner_console_markup.html.erb within layouts/inlined_string (0.2ms)
  Rendered /Users/richard/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/web-console-3.1.1/lib/web_console/templates/_prompt_box_markup.html.erb within layouts/inlined_string (0.2ms)
  Rendered /Users/richard/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/web-console-3.1.1/lib/web_console/templates/style.css.erb within layouts/inlined_string (0.3ms)
  Rendered /Users/richard/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/web-console-3.1.1/lib/web_console/templates/console.js.erb within layouts/javascript (47.5ms)
  Rendered /Users/richard/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/web-console-3.1.1/lib/web_console/templates/main.js.erb within layouts/javascript (0.4ms)
  Rendered /Users/richard/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/web-console-3.1.1/lib/web_console/templates/index.html.erb (96.1ms)
```

I've digged trough the route_translator lib code but couldn't find any clues that would point as to why this functionality would break. Wasn't sure if an issue here would be the right place but hope that someone here has a clue!

I've setup the test repository here: https://github.com/richardvenneman/route-translator-rails5-collection-caching

**Comment by tagliala** [comment]
This is the offending code. After including this, application will raise that error. An initializer inside the rails application does not cause this

```rb
module ActionController
  class Base
  end
end
```

Any help would be very appreciated

**Comment by richardvenneman** [comment]
Thanks for the reply @tagliala. I'm not sure if I'm skilled enough/able to help out here. Do you mean that the ActionController extensions should be moved to a module and included from within an initializer?

**Comment by tagliala** [comment]
> Do you mean that the ActionController extensions should be moved to a module and included from within an initializer?

No, I mean that if you create an initializer with that very same code inside a newly generated rails application, you will not get errors.

It's not the code per-se, it should be something else. I'm taking a look but I don't know if I'm skilled enough to solve this

**Comment by tagliala** [comment]
Think I got it. Please give a try

**Comment by richardvenneman** [comment]
@tagliala It works with the [8377d3361fbb650c628af457bba6ad1d0abfbb9a](latest commit), thanks! 👌 So I think we can mark this issue as solved.

One thing however: a certain method seems to be unavailable in my test suite at the latest commit:

```
NoMethodError: undefined method `optimize_routes_generation?' for #<CitiesControllerTest:0x007fe3a3345e20>
```

I think there was some TestCase support code recently removed from this gem but cannot find the exact commit anymore.

**Comment by tagliala** [comment]
that's right. Could you please provide a failing test case?

**Comment by tagliala** [comment]
This is the offending commit: https://github.com/enriclluelles/route_translator/commit/b77eaec0cd6406d6056061cbfe57d3dd9bf99e48

I just need a failing test case so this will not happen again 'cause at the moment all tests pass

**Comment by richardvenneman** [comment]
Don't have a template but this is a failing example.

Controller:

```ruby
class ContinentsController < ApplicationController
  def show
    redirect_to(root_path, status: 303) && return
  end
end
```

Test:

```ruby
require 'test_helper'

class ContinentsControllerTest < ActionController::TestCase
  test "redirects show to root" do
    get :show, params: { id: 'europe' }

    assert_redirected_to root_path
  end
end
```

Error:

```shell
Error:
ContinentsControllerTest#test_redirects_show_to_root:
NoMethodError: undefined method `optimize_routes_generation?' for #<ContinentsControllerTest:0x007fe39d8283a8>
    test/controllers/continents_controller_test.rb:7:in `block in <class:ContinentsControllerTest>'


bin/rails test test/controllers/continents_controller_test.rb:4
```

**Comment by tagliala** [comment]
Thanks, please give a try

**Comment by richardvenneman** [comment]
Works perfectly, thanks a lot! 🙏
