### ISSUE TITLE
params in url worked in 2.0.1 but not any more in 3.0.1

### ISSUE THREAD

**Issue by optimum-dulopin** [enriclluelles/route_translator#23]
hi,
with route_translator 2.0.1, I had route.rb like this 
    get 'products_path', :controller => 'products', :action => 'index', :constraints => { :city_id => /\d+/, :category_id => /\d+/, :user_id => /\d+/, :subcategory_id => /\d+/, :prefixid => /[A-Z]{3}/}, :as => :products

and in my i18n-routes.yml
fr:
  products_path: "(:userslug(-:user_id)/)articles(/:categoryslug-:rubrique_id(/:subcategoryslug-:subcategory_id))(/:cityslug-_:city_id)(/:productslug-:prefixid:id)(/:action)"

en:
  products_path: "(:userslug(-:user_id)/)products(/:categoryslug-:rubrique_id(/:subcategoryslug-:subcategory_id))(/:cityslug-_:city_id)(/:productslug-:prefixid:id)(/:action)"

and it was working perfectly
but since I updated to 3.0.1 , I have this error and I can't figure why

NoMethodError (undefined method `city_id' for #<ActionDispatch::Request:0x000000072515a0>):
  journey (1.0.4) lib/journey/router.rb:133:in`block (2 levels) in find_routes'
  journey (1.0.4) lib/journey/router.rb:133:in `each'
  journey (1.0.4) lib/journey/router.rb:133:in`all?'
  journey (1.0.4) lib/journey/router.rb:133:in `block in find_routes'
  journey (1.0.4) lib/journey/router.rb:132:in`each'
  journey (1.0.4) lib/journey/router.rb:132:in `find_all'
  journey (1.0.4) lib/journey/router.rb:132:in`find_routes'
  journey (1.0.4) lib/journey/router.rb:56:in `call'
  actionpack (3.2.13) lib/action_dispatch/routing/route_set.rb:612:in`call'
  newrelic_rpm (3.6.1.88) lib/new_relic/rack/error_collector.rb:12:in `call'
  newrelic_rpm (3.6.1.88) lib/new_relic/rack/agent_hooks.rb:18:in`call'
  newrelic_rpm (3.6.1.88) lib/new_relic/rack/browser_monitoring.rb:16:in `call'
  warden (1.2.1) lib/warden/manager.rb:35:in`block in call'
  warden (1.2.1) lib/warden/manager.rb:34:in `catch'
  warden (1.2.1) lib/warden/manager.rb:34:in`call'
  actionpack (3.2.13) lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
  rack (1.4.5) lib/rack/etag.rb:23:in`call'
  rack (1.4.5) lib/rack/conditionalget.rb:25:in `call'
  actionpack (3.2.13) lib/action_dispatch/middleware/head.rb:14:in`call'
  actionpack (3.2.13) lib/action_dispatch/middleware/params_parser.rb:21:in `call'
  actionpack (3.2.13) lib/action_dispatch/middleware/flash.rb:242:in`call'
  rack (1.4.5) lib/rack/session/abstract/id.rb:210:in `context'
  rack (1.4.5) lib/rack/session/abstract/id.rb:205:in`call'
  actionpack (3.2.13) lib/action_dispatch/middleware/cookies.rb:341:in `call'
  activerecord (3.2.13) lib/active_record/query_cache.rb:64:in`call'
  activerecord (3.2.13) lib/active_record/connection_adapters/abstract/connection_pool.rb:479:in `call'
  actionpack (3.2.13) lib/action_dispatch/middleware/callbacks.rb:28:in`block in call'
  activesupport (3.2.13) lib/active_support/callbacks.rb:405:in `_run__2146773877232852005__call__139502699737427917__callbacks'
  activesupport (3.2.13) lib/active_support/callbacks.rb:405:in`__run_callback'
  activesupport (3.2.13) lib/active_support/callbacks.rb:385:in `_run_call_callbacks'
  activesupport (3.2.13) lib/active_support/callbacks.rb:81:in`run_callbacks'
  actionpack (3.2.13) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (3.2.13) lib/action_dispatch/middleware/remote_ip.rb:31:in`call'
  actionpack (3.2.13) lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
  actionpack (3.2.13) lib/action_dispatch/middleware/show_exceptions.rb:56:in`call'
  railties (3.2.13) lib/rails/rack/logger.rb:32:in `call_app'
  railties (3.2.13) lib/rails/rack/logger.rb:16:in`block in call'
  activesupport (3.2.13) lib/active_support/tagged_logging.rb:22:in `tagged'
  railties (3.2.13) lib/rails/rack/logger.rb:16:in`call'
  actionpack (3.2.13) lib/action_dispatch/middleware/request_id.rb:22:in `call'
  rack (1.4.5) lib/rack/methodoverride.rb:21:in`call'
  rack (1.4.5) lib/rack/runtime.rb:17:in `call'
  activesupport (3.2.13) lib/active_support/cache/strategy/local_cache.rb:72:in`call'
  rack (1.4.5) lib/rack/lock.rb:15:in `call'
  actionpack (3.2.13) lib/action_dispatch/middleware/static.rb:63:in`call'
  rack-cache (1.2) lib/rack/cache/context.rb:136:in `forward'
  rack-cache (1.2) lib/rack/cache/context.rb:245:in`fetch'
  rack-cache (1.2) lib/rack/cache/context.rb:185:in `lookup'
  rack-cache (1.2) lib/rack/cache/context.rb:66:in`call!'
  rack-cache (1.2) lib/rack/cache/context.rb:51:in `call'
  railties (3.2.13) lib/rails/engine.rb:479:in`call'
  railties (3.2.13) lib/rails/application.rb:223:in `call'
  railties (3.2.13) lib/rails/railtie/configurable.rb:30:in`method_missing'
  unicorn (4.6.2) lib/unicorn/http_server.rb:552:in `process_client'
  unicorn (4.6.2) lib/unicorn/http_server.rb:632:in`worker_loop'
  newrelic_rpm (3.6.1.88) lib/new_relic/agent/instrumentation/unicorn_instrumentation.rb:22:in `call'
  newrelic_rpm (3.6.1.88) lib/new_relic/agent/instrumentation/unicorn_instrumentation.rb:22:in`block (4 levels) in <top (required)>'
  unicorn (4.6.2) lib/unicorn/http_server.rb:500:in `spawn_missing_workers'
  unicorn (4.6.2) lib/unicorn/http_server.rb:142:in`start'
  unicorn (4.6.2) bin/unicorn:126:in `<top (required)>'
  /home/railsskelbimai/.rvm/gems/ruby-1.9.3-p392/bin/unicorn:19:in`load'
  /home/railsskelbimai/.rvm/gems/ruby-1.9.3-p392/bin/unicorn:19:in `<main>'
  /home/railsskelbimai/.rvm/gems/ruby-1.9.3-p392/bin/ruby_noexec_wrapper:14:in`eval'
  /home/railsskelbimai/.rvm/gems/ruby-1.9.3-p392/bin/ruby_noexec_wrapper:14:in `<main>'

isnt it possible anymore to have params in url ?

thanks
