### ISSUE TITLE
Undefined method `available_locales='

### ISSUE THREAD

**Issue by jguitar** [enriclluelles/route_translator#100]
New setup values are not working on 4.0.0 release. As a workaround I have used master branch.

**Comment by tagliala** [comment]
which setup values?

**Comment by tagliala** [comment]
Ok got it: https://github.com/enriclluelles/route_translator/commit/cf459f554429eee938c1348fc75530ef1e908bc1

This was added after the 4.0.0 release. That's one of the reason why I prefer a `develop` branch.

**Comment by jguitar** [comment]
Yes, I installed the gem today, and read the _README_. So, I tried to use the new setup values, but current gem version is different than master branch.

Now, that there is not a real issue, you can let it open or close it.

**Comment by tagliala** [comment]
@jguitar you are perfectly right. I'm going to leave this open for reference

**Comment by tagliala** [comment]
4.1.0 released, this should not be an issue anymore
